"""create users table with admin

Revision ID: d19241fe0efb
Revises:
Create Date: 2026-02-20 16:31:26.767889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from passlib.context import CryptContext


# revision identifiers, used by Alembic.
revision: str = "d19241fe0efb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "roles",
            sa.Enum("SUPERADMIN", "ADMIN", "USER", name="userrole"),
            nullable=True,
        ),
        sa.Column("added_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("time_added", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###

    # --- Custom Data Migration ---
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    hashed_pwd = pwd_context.hash("admin")
    op.execute(
        f"""
        INSERT INTO users (username, email, hashed_password, is_active, is_deleted, roles, time_added, last_update_time)
        VALUES ('admin', 'admin@example.com', '{hashed_pwd}', True, False, 'SUPERADMIN', NOW(), NOW())
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
